### ISSUE TITLE
Having some issues building

### ISSUE THREAD

**Issue by saikat0511** [Rebellion-Hub/Manifest#1]
FAILED: /home/saikatpatra/rebellion_ten/out/soong/build.ninja
/home/saikatpatra/rebellion_ten/out/soong/.bootstrap/bin/soong_build -t -l /home/saikatpatra/rebellion_ten/out/.module_paths/Android.bp.list -b /home/saikatpatra/rebellion_ten/out/soong -n /home/saikatpatra/rebellion_ten/out -d /home/saikatpatra/rebellion_ten/out/soong/build.ninja.d -globFile /home/saikatpatra/rebellion_ten/out/soong/.bootstrap/build-globs.ninja -o /home/saikatpatra/rebellion_ten/out/soong/build.ninja Android.bp
error: vendor/rebellion/build/soong/Android.bp:30:8: module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'
21:48:58 soong bootstrap failed with: exit status 1

#### failed to build some targets (31 seconds) ####

**Comment by saikat0511** [comment]
any help is appreciated, i am a newbie

**Comment by Abhat27** [comment]
It's fixed! Pm me in telegram
t.me/Abhat27
